# Generated by Django 5.1.1 on 2024-10-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserIN',
        ),
    ]
